# Generated by Django 2.1.5 on 2019-02-10 05:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('nick_name', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('updated_date', models.DateField()),
                ('created_date', models.DateField()),
                ('investor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_picker.Investor')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=254, unique=True)),
                ('exchange', models.CharField(max_length=254, unique=True)),
                ('industry', models.CharField(max_length=254, unique=True)),
                ('sector', models.CharField(max_length=254, unique=True)),
                ('website', models.URLField(unique=True)),
                ('description', models.CharField(max_length=254, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('earnings_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('financials_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('market_cap', models.BigIntegerField()),
                ('beta', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
