# Generated by Django 2.1.5 on 2019-02-10 08:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='EBITDA',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='cash_flow',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='consensus_EPS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='day200_moving_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='day50_moving_avg',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='debt',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend_yield',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ex_dividend_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='gross_profit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='insider_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_EPS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_EPS_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='logo',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='number_of_estimates_EPS',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='peers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_to_book',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_on_assets',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_on_capital',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_on_equity',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='revenue',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='shares_outstanding',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ttmEPS',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week52high',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='week52low',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investoraccount',
            name='updated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='beta',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
