# Generated by Django 2.1.5 on 2019-02-24 03:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0002_auto_20190210_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='earnings_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='financials_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
