# Generated by Django 2.1.5 on 2019-02-24 03:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0003_auto_20190224_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stock',
            name='earnings_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stock',
            name='financials_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stock',
            name='logo',
            field=models.URLField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
