# Generated by Django 2.1.5 on 2019-02-24 03:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0004_auto_20190224_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='earnings_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='stock',
            name='financials_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
