# Generated by Django 2.1.5 on 2019-02-24 03:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0005_auto_20190224_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='earnings_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='stock',
            name='financials_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
