# Generated by Django 2.1.5 on 2019-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0006_auto_20190224_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares_outstanding',
            field=models.BigIntegerField(null=True),
        ),
    ]
