# Generated by Django 2.1.5 on 2019-03-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0007_auto_20190224_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
