# Generated by Django 2.1.5 on 2019-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_picker', '0008_auto_20190303_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='iexId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='isEnabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ref_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
